"""Add streak and onboarding in UserProfile

Revision ID: 1f5e4f66e44e
Revises: 4e1966a46b76
Create Date: 2026-09-05 18:30:20.792023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5e4f66e44e'
down_revision = '4e1966a46b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('onboarding', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('onboarding')
        batch_op.drop_column('streak')

    # ### end Alembic commands ###
