"""Add user profile, subject, chapter, chapterprogress and chapterporgresslog

Revision ID: afd8dc25e9b1
Revises: 057889f60253
Create Date: 2026-09-05 16:01:40.802714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd8dc25e9b1'
down_revision = '057889f60253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chapter_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_progress_chapter_id'), ['chapter_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_chapter_progress_user_id'), ['user_id'], unique=True)

    op.create_table('chapter_progress_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_progress_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_progress_log_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_progress_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('chapter_progress_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_progress_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_progress_log_chapter_id'))

    op.drop_table('chapter_progress_log')
    with op.batch_alter_table('chapter_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_progress_chapter_id'))

    op.drop_table('chapter_progress')
    op.drop_table('user_profiles')
    op.drop_table('chapters')
    op.drop_table('subjects')
    # ### end Alembic commands ###
