"""Remove index from chapter progress and its log

Revision ID: b3b21276be99
Revises: 1f5e4f66e44e
Create Date: 2026-09-05 20:12:39.982249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b21276be99'
down_revision = '1f5e4f66e44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_progress_chapter_id'))
        batch_op.drop_constraint(batch_op.f('ix_chapter_progress_user_id_chapter_id'), type_='unique')

    with op.batch_alter_table('chapter_progress_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_progress_log_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_progress_log_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_progress_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_progress_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_progress_log_chapter_id'), ['chapter_id'], unique=False)

    with op.batch_alter_table('chapter_progress', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('ix_chapter_progress_user_id_chapter_id'), ['user_id', 'chapter_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_chapter_progress_chapter_id'), ['chapter_id'], unique=True)

    # ### end Alembic commands ###
